source 'https://rubygems.org'
gem 'compass'
gem 'bootstrap-sass', '~> 2.1.0.0'

gem 'kramdown'
gem 'middleman', '~> 3.2.2'
gem 'middleman-livereload'
gem 'middleman-syntax'
gem 'rb-fsevent'
gem 'pry'
gem 'middleman-pry'